### ISSUE TITLE
Version in pyproject.toml is wrong

### ISSUE THREAD

**Issue by carlsmedstad** [coveooss/json-schema-for-humans#146]
The version in pyproject.toml is wrong:

```toml
[tool.poetry]
name = "json-schema-for-humans"
version = "0.41.0"
```

Is this not the version that is used when building the PyPI package?

It might be a good idea to implement something like https://pypi.org/project/poetry-dynamic-versioning/ to not have to manually bump the version.
