### ISSUE TITLE
Add custom schema version to generated documentation

### ISSUE THREAD

**Issue by eeintech** [coveooss/json-schema-for-humans#237]
Hello there,

I am not sure if this feasible, would it be possible to display the custom schema version in the generated doc?

It could go under the title:
![image](https://github.com/coveooss/json-schema-for-humans/assets/4020546/a87b3cac-d1f9-46da-872c-9217a2200800)

And one could set via adding it to the custom schema via `schema_version` key, example:
``` yaml
$schema: http://json-schema.org/draft-07/schema#
title: My custom schema
description: This is my custom schema, see the version above.
version: 1.0.0
```

Thanks a lot!
