### ISSUE TITLE
Missing space in lists when generating MKDocs

### ISSUE THREAD

**Issue by pareion** [coveooss/json-schema-for-humans#262]
Hello!

We just started using this library and find it excellent. There is however a few minor issues when generating the MKDoc files.

For example when generating lists they end up in one string instead of a list of elements:
![billede](https://github.com/user-attachments/assets/e3cc9a21-11b7-4524-baed-9355bc264889)

We're using the following schema definition:
```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "title": "Bizzkit deployment",
  "type": "object",
  "description": "Configuration of the Bizzkit deployment Helm chart.",
  "properties": {
    "global": {
      "$schema": "https://json-schema.org/draft/2019-09/schema",
      "type": "object",
      "description": "Configuration of the global property shared across all Bizzkit Helm charts to ensure cross-compatibility.",
      "properties": {
        "environment": {
          "type": "string",
          "description": "Environment in which the chart is deployed.",
          "default": "dev",
          "enum": [
            "test",
            "dev",
            "stage",
            "prod"
          ]
        }
      }
    }
  },
  "additionalProperties": false
}
```

The following json-schema-for-humans configuration
```
template_name: md
show_toc: False
with_footer: False
examples_as_yaml: True
template_md_options:
  badge_as_image: True
  show_heading_numbers: False
  properties_table_columns:
  - Property
  - Type
  - Title/Description
```

I suggest adding a new line in the `json_schema_for_humans/templates/md/section_one_of.md` file, but I'm not sure if it breaks anything.
